spring:
  application:
    name: kata-bank
kata:
  bank:
    adapter:
      persistance:
        mongo:
          enabled: true

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 5.0.14
