spring:
  application:
    name: kata-bank
kata:
  bank:
    adapter:
      persistance:
        mongo:
          enabled: true
        jpa:
          enabled: false



#  datasource:
#    url: jdbc:postgresql://localhost:5432/test
#    username: amine
#    password: amine123*
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
